site_name: Copilot camp
site_url: https://microsoft.github.io/copilot-camp
repo_url: https://github.com/microsoft/copilot-camp
repo_name: microsoft/copilot-camp
edit_uri: ''                    # Disable edit button
extra_css:
    - assets/labStyles.css
nav: 
- Home: 'index.md'
- Path A - Extend Copilot: 
  - Welcome : 'pages/extend-m365-copilot/index.md'
  - Lab A0 - Prerequisites: 'pages/extend-m365-copilot/00-prerequisites.md'
  - Lab A1 - Declarative Copilot: 'pages/extend-m365-copilot/01-declarative-copilot.md'
  - Lab A2 - First API Plugin: 'pages/extend-m365-copilot/02-api-plugin.md'
  - Lab A3 - Enhanced API Plugin: 'pages/extend-m365-copilot/03-enhance-api-plugin.md'
  - Lab A4 - Add Adaptive Cards: 'pages/extend-m365-copilot/04-add-adaptive-card.md'
  - Lab A5 - Add a Declarative Copilot: 'pages/extend-m365-copilot/05-add-declarative-copilot.md'
  - Lab A6 - Add authentication: 'pages/extend-m365-copilot/06-add-authentication.md'
- Path B Build Your Own Copilot: 
  - Welcome : 'pages/custom-engine/index.md'
  - Lab B0 - Prerequisites: 'pages/custom-engine/00-prerequisites.md'
  - Lab B1 - Build a custom engine copilot using Azure OpenAI and Teams Toolkit: 'pages/custom-engine/01-custom-engine-copilot.md'
  - Lab B2 - Index your data in Azure AI Search and bring it into your custom engine copilot: 'pages/custom-engine/02-rag.md'
  - Lab B3 - Enhance user experience with the Powered by AI kit: 'pages/custom-engine/03-powered-by-ai.md'
  - Lab B4 - Add actions to handle complex tasks: 'pages/custom-engine/04-actions.md'
  - Lab B5 - Secure your solution using authentication: 'pages/custom-engine/05-authentication.md'
theme:
  name: 'material'
  palette: 
    primary: '#35258F'
    accent: '#091F2C'
  logo: 'assets/images/logo-copilot-camp.jpg'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs         # Top nav
    - navigation.tabs.sticky  # Make top nav stay vaisible
    - navigation.sections
    - toc.integrate           # Integrate sections into left nav
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      base_path: docs/includes
  - attr_list
extra_javascript:
  - javascripts/next-button.js