site_name: Copilot camp
site_url: https://microsoft.github.io/copilot-camp
repo_url: https://github.com/microsoft/copilot-camp
repo_name: microsoft/copilot-camp
edit_uri: ''                    # Disable edit button
extra_css:
    - assets/labStyles.css
nav: 
- Home: 'index.md'
- Path A Extend Copilot: 
  - Welcome : 'pages/extend-m365-copilot/index.md'
  - Lab A0 - Prerequisites: 'pages/extend-m365-copilot/00-prerequisites.md'
  - Lab A1 - Declarative Copilot: 'pages/extend-m365-copilot/01-declarative-copilot.md'
  - Lab A2 - First API Plugin: 'pages/extend-m365-copilot/02-api-plugin.md'
  - Lab A3 - Enhanced API Plugin: 'pages/extend-m365-copilot/03-enhance-api-plugin/'
  - Lab A4 - Add Adaptive Cards: 'pages/extend-m365-copilot/04-add-adaptive-card/'
  - Lab A5 - Add a Declarative Copilot: 'pages/extend-m365-copilot/05-add-declarative-copilot/'
  - Lab A6 - Add authentication: 'pages/extend-m365-copilot/06-add-authentication/'
- Path B Build Your Own Copilot: 
  - Lab 00: 'pages/custom-engine/00-prerequisites.md'
  - Lab 01: 'pages/custom-engine/01-custom-engine-copilot.md'
  - Lab 02: 'pages/custom-engine/02-rag.md'
theme:
  name: 'material'
  palette: 
    primary: '#35258F'
    accent: '#091F2C'
  #logo: 'assets/microsoftteams_appcamp-webheader3.png'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs         # Top nav
    - navigation.tabs.sticky  # Make top nav stay vaisible
    - navigation.sections
    - toc.integrate           # Integrate sections into left nav
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      base_path: docs/includes
  - attr_list