site_name: Copilot camp
site_url: https://microsoft.github.io/copilot-camp
repo_url: https://github.com/microsoft/copilot-camp
repo_name: microsoft/copilot-camp
edit_uri: ''                    # Disable edit button
extra_css:
    - assets/labStyles.css
nav: 
- Home: 'index.md'
- Path A1 Extend Copilot: 
  - Welcome : 'pages/api-plugin/index.md'
  - Lab 00: 'pages/api-plugin/00-prerequisites.md'
  - Lab 01: 'pages/api-plugin/01-declarative-copilot.md'
  - Lab 02: 'pages/api-plugin/02-api-plugin.md'
- Path B Build Your Own Copilot: 
  - Lab 00: 'pages/custom-engine/00-prerequisites.md'
  - Lab 01: 'pages/custom-engine/01-custom-engine-copilot.md'
  - Lab 02: 'pages/api-plugin/02-rag.md'
theme:
  name: 'material'
  palette: 
    primary: '#35258F'
    accent: '#091F2C'
  #logo: 'assets/microsoftteams_appcamp-webheader3.png'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs         # Top nav
    - navigation.tabs.sticky  # Make top nav stay vaisible
    - navigation.sections
    - toc.integrate           # Integrate sections into left nav
markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list